--- Create_Warehouse ---

CREATE OR REPLACE WAREHOUSE ESP_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE ESP_WH;


--- Create_Database ---


CREATE OR REPLACE DATABASE ESP_DB;

USE DATABASE ESP_DB;


--- Create_Schemas ---


CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA CURATED;
CREATE OR REPLACE SCHEMA ANALYTICS;


--- Create_File_Format ---


USE DATABASE ESP_DB;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
DATE_FORMAT = 'YYYY-MM-DD'
EMPTY_FIELD_AS_NULL = TRUE;


--- Create_Storage_Integration ---


CREATE OR REPLACE STORAGE INTEGRATION ESP_S3_INTEGRATION
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::986948598904:role/snowflake-s3-role'
STORAGE_ALLOWED_LOCATIONS = ('s3://esp-data-lake-jayesh/');

DESC INTEGRATION ESP_S3_INTEGRATION;


--- Create_Stage ---


CREATE OR REPLACE STAGE ESP_STAGE
URL = 's3://esp-data-lake-jayesh/'
STORAGE_INTEGRATION = ESP_S3_INTEGRATION
FILE_FORMAT = CSV_FILE_FORMAT;

LIST @ESP_STAGE;